environment:
    deploy: deploy@somas.is

image: archlinux

secrets:
    - 661c57e5-ee95-4872-925d-d4b0d940ee38

sources:
    - https://github.com/somasis/www.somas.is

packages:
    - asciidoctor
    - go
    - jekyll
    - rsync

tasks:
    - dependencies: |
        sudo gem install -V --no-document --no-user-install \
            jekyll-asciidoc \
            jekyll-archives \
            jekyll-feed \
            jekyll-time-to-read \
            jekyll-sitemap \
            jekyll-seo-tag \
            jekyll-redirect-from
        go get git.sr.ht/~sircmpwn/openring
    - openring: |
        cd www.somas.is
        make OPENRING=~/go/bin/openring openring
    - build: |
        cd www.somas.is
        jekyll build --strict_front_matter
    - deploy: |
        cd www.somas.is
        rsync --rsh="ssh -o StrictHostKeyChecking=no" -vr _site/ ${deploy}:/srv/www/www.somas.is
