environment:
    deploy: deploy@somas.is

image: alpine/latest

secrets:
    - 661c57e5-ee95-4872-925d-d4b0d940ee38

sources:
    - https://github.com/somasis/www.somas.is
    - https://git.sr.ht/~sircmpwn/openring

packages:
    - asciidoctor
    - go
    - rsync
    - ruby
    - ruby-bigdecimal
    - ruby-dev
    - ruby-ffi
    - ruby-i18n

tasks:
    - dependencies: |
        sudo gem install -V jekyll jekyll-asciidoc jekyll-archives jekyll-feed \
            jekyll-time-to-read jekyll-sitemap jekyll-seo-tag
        cd openring
        go build
    - openring: |
        cd www.somas.is
        ../openring/openring \
            -s https://phidica.tumblr.com/rss \
            -s https://7596ff.com/rss.xml \
            -s https://leahneukirchen.org/blog/index.atom \
            -s https://leahneukirchen.org/trivium/index.atom \
            -s https://pikhq.com/index.xml \
            -s https://ewontfix.com/feed.rss \
            < _includes/webring_in.html \
            > _includes/webring_out.html
    - build: |
        cd www.somas.is
        jekyll build
    - deploy: |
        cd www.somas.is
        rsync --rsh="ssh -o StrictHostKeyChecking=no" -vr _site/ ${deploy}:/srv/www/www.somas.is
