kind: pipeline
type: docker
name: default

steps:
    - name: build
      image: jekyll/builder
      commands:
          - chown jekyll:jekyll .
          - apk add asciidoctor go
          - gem install --no-document --no-user-install jekyll-asciidoc jekyll-archives jekyll-time-to-read jekyll-seo-tag
          - go get -v git.sr.ht/~sircmpwn/openring
          - make OPENRING=~/go/bin/openring openring
          - jekyll build --strict_front_matter
    - name: deploy
      image: drillster/drone-rsync
      settings:
          user: deploy
          key:
              from_secret: deploy_angela.somas.is_20200701
          hosts: angela.somas.is
          source: ./_site/
          target: /srv/www/www.somas.is
          recursive: true
          delete: true
