title: "~somasis"

age: 21
gender: woman
description: >-
    likes philosophy, music, maps, and computers (sometimes)

author: "Somasis / Kylie J. McClain"

url: "https://www.somas.is"
lang: "en-US"

plugins:
    - jekyll-asciidoc
    - jekyll-feed
    - jekyll-time-to-read
    - jekyll-sitemap
    - jekyll-seo-tag

asciidoc: {}
asciidoctor:
    base_dir: :docdir
    safe: unsafe
    attributes:
        - idseparator=_
        - source-highlighter=coderay
        - icons=font

