title: "~somasis"

description: >-
    22 year old who likes philosophy, music, maps, and computers (sometimes)

author: "Kylie McClain"

url: "https://www.somas.is"
lang: "en-US"

defaults:
    -
        scope:
            path: ""
        values:
            layout: "post"

plugins:
    - jekyll-asciidoc
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-time-to-read
    - jekyll-redirect-from
    - jekyll-archives

asciidoc: {}
asciidoctor:
    base_dir: :docdir
    safe: unsafe
    attributes:
        - idseparator=_
        - source-highlighter=coderay
        - icons=font

jekyll-archives:
    enabled:
        - year
        - month
        - tags
        - categories
    layout: archive
    layouts:
        category: category
    permalinks:
        year: '/:year/'
        month: '/:year/:month/'
        tag: '/tag/:name/'
        category: '/:name/'
